# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
